---
- name: Install dev env
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Set hostname
      ansible.builtin.include_tasks: tasks/hostname.yml
      vars:
        hostname: "debian-{{ query('community.general.random_string', length=4, upper=false, numbers=true, special=false)[0] }}"

    - name: Install zsh
      ansible.builtin.include_tasks: tasks/shell.yml

    - name: Setup new users
      ansible.builtin.include_tasks: tasks/users.yml

    - name: Setup dev tools and libs
      ansible.builtin.include_tasks: tasks/devtools.yml

    - name: Setup virtualization
      ansible.builtin.include_tasks: tasks/virt.yml

    - name: Setup apps
      ansible.builtin.include_tasks: tasks/apps.yml

    - name: Setup yubikey
      ansible.builtin.include_tasks: tasks/yubikey.yml
