---
- name: Install kernel header
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - linux-headers-generic

- name: Install Python build dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - curl
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - liblzma-dev

- name: Install C/C++ development tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - autotools-dev
    - autoconf
    - cmake
    - vim
    - emacs
    - git

- name: Install OpenJDK
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - openjdk-17-jdk
    - openjdk-17-docs
    - openjdk-17-demo
    - openjdk-17-dbg
    - openjdk-17-source
    - maven
    - gradle

- name: Add dotnet repo
  ansible.builtin.apt:
    deb: https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb

- name: Install Dotnet
  ansible.builtin.apt:
    name: dotnet-sdk-7.0