---
- name: Setup fcitx
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install Fcitx on Debian
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - fcitx
        - fcitx-unikey
        - fcitx-rime
        - fcitx-mozc

    - name: Install Noto fonts on Debian
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - fonts-noto
        - fonts-croscore
      when: ansible_os_family == "Debian"