---
- name: Install necessary fonts
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Noto fonts on OpenSUSE Leap
      become: true
      community.general.zypper:
        name: "{{ item }}" 
        type: pattern
        state: present
      with_items:
        - "noto-fonts google-noto-{sans,serif}-{tc,sc,hk,jp,kr}-fonts-full"
        - google-croscore-fonts
      when: ansible_os_family == "Suse" and ansible_distribution == "openSUSE Tumbleweed"

    - name: Install Noto fonts on OpenSUSE Leap
      become: true
      community.general.zypper:
        name: "{{ item }}" 
        type: pattern
        state: present
      with_items:
        - "noto-*"
        - google-croscore-fonts
      when: ansible_os_family == "Suse" and ansible_distribution = "openSUSE Leap"

    - name: Install Noto fonts on Debian
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - fonts-noto
        - fonts-croscore
      when: ansible_os_family == "Debian"
