---
- name: Setup fcitx
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Fcitx on OpenSUSE
      become: true
      community.general.zypper:
        name: "{{ item }}"
        type: pattern
        state: present
      with_items:
        - fcitx
        - fcitx-unikey
        - fcitx-rime
        - fcitx-mozc
      when: ansible_os_family == "Suse"

    - name: Install KVM on Debian
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - fcitx
        - fcitx-unikey
        - fcitx-rime
        - fcitx-mozc
      when: ansible_os_family == "Debian"