---
- name: Add user "{{ item }}"
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - sudo
    shell: /bin/zsh
    state: present

- name: Add authorized key
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'authorized_keys/' + item) }}"

- name: Copy .zshrc to {{ item }}
  ansible.builtin.copy:
    src: files/shell/zshrc
    dest: /home/{{ item }}/.zshrc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
