---
- name: Install neccessary tools for Yubikey on Debian
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - gnupg2
    - gnupg-agent
    - dirmngr
    - cryptsetup
    - scdaemon
    - pcscd
    - secure-delete
    - yubikey-personalization
