---
- name: Install desktop tools for workstation usecase
  become: true
  become_method: sudo
  tasks:
    - name: Install the container tools
      ansible.builtin.dnf:
        name:
          - distrobox
          - lxc
          - lxc-templates
        state: latest
