---
# tasks file for layered
- name: Cancel current rpm-ostree process
  ansible.builtin.command: rpm-ostree cancel

- name: Install desired applications as layered packages
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  loop: "{{ layered_package_install }}"

- name: Remove applications from the base OS
  ansible.builtin.command: rpm-ostree override remove {{ item }}
  become: yes
  become_method: sudo
  loop: "{{ base_package_remove }}"

- name: Make sure base OS is upgraded to the latest
  shell: rpm-ostree upgrade

- name: Query whether booted RPM-OSTree deployment is first deployment
  shell: rpm-ostree status --json | jq -r .deployments[0].booted
  register: booted

- name: Reboot if new deployement is ready.
  reboot:
    reboot_timeout: 300
  become: yes
  when:
    - booted.stdout == "false"