---
- name: Install container tools & libraries
  become: true
  become_method: sudo
  tasks:
    - name: Install podman
      ansible.builtin.apt:
        name:
          - podman
        state: latest

    - name: Install lxc
      ansible.builtin.apt:
        name:
          - lxc
          - libvirt0
          - libpam-cgfs
          - bridge-utils
          - uidmap
        state: latest
