- become: true
- name: Install the 'Development tools' package group
  ansible.builtin.dnf:
    name:
      - fcitx5
      - fcitx5-autostart
      - fcitx5-mozc
      - fcitx5-rime
      - fcitx5-unikey
      - distrobox
      - libvirt-daemon
      - libvirt-daemon-config-network
      - libvirt-daemon-driver-interface
      - libvirt-daemon-driver-network
      - libvirt-daemon-driver-nwfilter
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-driver-secret
      - libvirt-daemon-driver-storage-core
      - qemu-kvm
      - virt-manager
      - lxc
      - lxc-templates
      - pam-u2f
      - pam_yubico
      - pamu2fcfg
      - yubikey-manager
      - zsh
    state: latest
