---
- become: true
- name: Install virtualization
  ansible.builtin.dnf:
    name:
      - "@Virtualization Client"
      - "@Virtualization Hypervisor"
      - "@Virtualization Platform"
      - "@Virtualization Tools"
    state: latest
